// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjs0tEVpXdOQtnnEVIC1r9zRN-1vEoLLs',
    appId: '1:848195301579:web:31f5599f432feb9cabeb4e',
    messagingSenderId: '848195301579',
    projectId: 'cookiesshop-be8f9',
    authDomain: 'cookiesshop-be8f9.firebaseapp.com',
    storageBucket: 'cookiesshop-be8f9.appspot.com',
    measurementId: 'G-4CLL0XKXCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjldUOT209t2YdZlj2qYgh_hoRFJp98tI',
    appId: '1:848195301579:android:998051638959404aabeb4e',
    messagingSenderId: '848195301579',
    projectId: 'cookiesshop-be8f9',
    storageBucket: 'cookiesshop-be8f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuJmLp7qFGoBHKozlralIde_xq9mtT9A',
    appId: '1:848195301579:ios:4b698c66ce05e871abeb4e',
    messagingSenderId: '848195301579',
    projectId: 'cookiesshop-be8f9',
    storageBucket: 'cookiesshop-be8f9.appspot.com',
    iosBundleId: 'com.example.cookiesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjuJmLp7qFGoBHKozlralIde_xq9mtT9A',
    appId: '1:848195301579:ios:4b698c66ce05e871abeb4e',
    messagingSenderId: '848195301579',
    projectId: 'cookiesshop-be8f9',
    storageBucket: 'cookiesshop-be8f9.appspot.com',
    iosBundleId: 'com.example.cookiesShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjs0tEVpXdOQtnnEVIC1r9zRN-1vEoLLs',
    appId: '1:848195301579:web:b3383fb44829596eabeb4e',
    messagingSenderId: '848195301579',
    projectId: 'cookiesshop-be8f9',
    authDomain: 'cookiesshop-be8f9.firebaseapp.com',
    storageBucket: 'cookiesshop-be8f9.appspot.com',
    measurementId: 'G-W64F1NM4SR',
  );
}
